theme: "github.com/theNewDynamic/gohugo-theme-ananke"
canonifyURLs: false
baseURL: 'https://mapf0ld.github.io/'
publishDir: "docs"
languageCode: "ja"
defaultContentLanguage: "ja"
hasCJKLanguage: true
title: 'Hiroyuki Log'

author:
  twitter: "https://twitter.com/mapf0ld"

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 100



#[taxonomies]
#tag = "tags"
#cagtegory = "categories"
#archive = "archives"
