theme: "github.com/theNewDynamic/gohugo-theme-ananke"
canonifyURLs: false
baseURL: "https://mapf0ld.github.io/"
publishDir: "docs"
languageCode: "ja"
defaultContentLanguage: "ja"
hasCJKLanguage: true
title: "Tsukahara Log"

author:
  twitter: "https://twitter.com/mapf0ld"

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 100

params:
  ananke_socials:
    - name: twitter
      url: https://twitter.com/mapf0ld
    - name: github
      url: https://github.com/mapf0ld
    - name: instagram
      url: https://instagram.com/vertexion

  show_reading_time: true
#[taxonomies]
#tag = "tags"
#cagtegory = "categories"
#archive = "archives"
